### ISSUE TITLE
Typos in description

### ISSUE THREAD

**Issue by wsvincent** [rzashakeri/django-audio-validator#2]
There seem to be a few typos in your About description. Perhaps something like the following?

An audio validator for Django with MIME type and file extension checking.

**Comment by rzashakeri** [comment]
> 

Thank you for what you said
Spelling error corrected 🙏
This project has been archived and instead of this I made a more complete library with which you can validate all types of files, the new project has been tested and also supports more types, you can access it through the following link:
[file validator](https://github.com/rzashakeri/file_validator)
